---
.do_variables: &do_variables
  PRIVATE_KEY: $DO_PRIVATE_KEY
  CI_PLATFORM: "do"
  SSH_USER: root

.do: &do
  extends: .testcases
  tags:
    - do

do_ubuntu-canal-ha:
  stage: deploy-part2
  extends: .do
  variables:
    <<: *do_variables
  when: manual
  except: ['triggers']
  only: ['master', /^pr-.*$/]
